### ISSUE TITLE
Update to use strong-error-handler

### ISSUE THREAD

**Issue by davidcheung** [strongloop/loopback-sandbox#10]
as per @richardpringle 's suggestion
update to use strong-error-handler, like how it would be scaffolded from workspace

related to https://github.com/strongloop/loopback/issues/1650

**Comment by loay** [comment]
@davidcheung Does  this commit https://github.com/strongloop/loopback-sandbox/commit/7b5ba1c4df2f7c76e3ed79e44119f08a8b6ad9f4
fix the issue?

**Comment by superkhau** [comment]
I recommend just rescaffolding the whole app -- run the Makefile via `make` to have this project regenerate itself. The point was to make it painless to upgrade.

**Comment by davidcheung** [comment]
@loay i believe the original intention was addressed(dont fully remember the original intention since it is quite long ago and i didnt write it down clearly), @superkhau are u talking about upgrading sandbox to 3.0, we could perhaps do it in another issue?

**Comment by superkhau** [comment]
>@superkhau are u talking about upgrading sandbox to 3.0, we could perhaps do it in another issue?

Yes, I see you guys upgrading strong-error-handler (which is in the new scaffold anyways I believe), so I thought you could just kill all these birds at the same time by rescaffolding the entire thing.
