### ISSUE TITLE
strong-remoting --  There is no method to handle GET /Contact3126664688727987007s

### ISSUE THREAD

**Issue by penzhan8451** [strongloop/loopback-sandbox#4]
Hi,

I hit by an issue for model rest api.   For multi-tenant support,  I  dynamically created new DS, and models for every user.  and plural is also different for every user.  For example, user1 model rest url is like '.../api/UsersAAAAs', user2 will be '.../api/UsersBBBBBs'.    One connector module is put to loopbackProj/node-modules.  

When user1 and user2 both post a request to create their DS and Models (attach to their DS and APP, model only has different name and plural),  user1's model rest api will not  be effect,  user2 model rest  api can work. 
For example,  access user

Could you please give me any comments?  Thanks very much!

**Comment by superkhau** [comment]
@penzhan8451 Are you still running into issues here? Please create the issue at https://github.com/strongloop/loopback/issues.
