### ISSUE TITLE
scope bug report 

### ISSUE THREAD

**Issue by bboalimoe** [strongloop/loopback-sandbox#6]
## issue description

here in [strongloop scope docs](https://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Scopes)
the default scope field didn't function as supposed 
## STR:
- create a datasource with mongo
- add the UserLocation.json file to the models dir
- done
## forked repo url:

https://github.com/bboalimoe/loopback-sandbox

**Comment by superkhau** [comment]
@bboalimoe Are you still running into issues? Please post at https://github.com/strongloop/loopback/issues instead since we don't really look here.
